<?php
require(dirname(__FILE__).DIRECTORY_SEPARATOR.'config.php');
return array(
	'homeUrl'=>$config['url'],
	'basePath'=>dirname(__FILE__).DIRECTORY_SEPARATOR.'..',
	'language'=>$config['lang'],
	'theme'=>$config['theme'],
	'preload'=>array('log'),
	'import'=>array(
		'application.models.*',
		'application.components.*',
	),
	'defaultController'=>'news',
	'modules'=>array(
		'admin',
		'stats',
	),
	'components'=>array(
		'user'=>array(
			'allowAutoLogin'=>true,
		),
		'ih'=>array(
			'class'=>'CImageHandler',
		),
		'urlManager'=>array(
			'urlFormat'=>'path',
			'showScriptName'=>false,
			'rules'=>require(dirname(__FILE__).DIRECTORY_SEPARATOR.'routes.php'),
		),
		'request'=>array(
			'enableCsrfValidation'=>true,
			'enableCookieValidation'=>true,
		),
		'cache'=>array(
			'class'=>$config['caching'],
		),
		'db'=>array(
			'connectionString'=>"mysql:host={$config['hostWeb']};port=3306;dbname={$config['dbnameWeb']}",
			'emulatePrepare'=>true,
			'username'=>$config['userWeb'],
			'password'=>$config['passWeb'],
			'charset'=>'utf8',
			'enableProfiling'=>true,
			'enableParamLogging'=>true,
			'schemaCachingDuration'=>3600,
		),
		'forum'=>array(
			'connectionString'=>"mysql:host={$config['hostForum']};port=3306;dbname={$config['dbnameForum']}",
			'class'=>'CDbConnection',
			'emulatePrepare'=>true,
			'username'=>$config['userForum'],
			'password'=>$config['passForum'],
			'tablePrefix'=>$config['prefixForum'],
			'charset'=>'utf8',
			'enableProfiling'=>true,
			'enableParamLogging'=>true,
			'schemaCachingDuration'=>3600,
		),
		'ls'=>array(
			'class'=>'CDbConnection',
			'connectionString'=>"mysql:host={$config['hostLs']};port=3306;dbname={$config['dbnameLs']}",
			'emulatePrepare'=>true,
			'username'=>$config['userLs'],
			'password'=>$config['passLs'],
			'charset'=>'utf8',
			'enableProfiling'=>true,
			'enableParamLogging'=>true,
			'schemaCachingDuration'=>3600,
		),
		'gs'=>array(
			'class'=>'CDbConnection',
			'connectionString'=>"mysql:host={$config['hostGs']};port=3306;dbname={$config['dbnameGs']}",
			'emulatePrepare'=>true,
			'username'=>$config['userGs'],
			'password'=>$config['passGs'],
			'charset'=>'utf8',
			'enableProfiling'=>true,
			'enableParamLogging'=>true,
			'schemaCachingDuration'=>3600,
		),
		'session'=>array(
			'class'=>'application.components.MyCDbHttpSession',
			'connectionID'=>'db',
			'sessionTableName'=>'session',
			'autoCreateSessionTable'=>false,
			'compareIpAddress'=>true,
			'compareUserAgent'=>true,
			'compareIpBlocks'=>0,
		),
		'errorHandler'=>array(
			'errorAction'=>'site/error',
		),
		'assetManager'=>array(
			'linkAssets'=>false,
		),
		'log'=>array(
			'class'=>'CLogRouter',
			'routes'=>array(
				array(
					'class'=>'CFileLogRoute',
					'levels'=>'error, warning',
					//'class'=>'CProfileLogRoute',
					//'report'=>'summary',
				),
				//array('class'=>'CWebLogRoute'),
			),
		),
	),
	'params'=>$params,
);